language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../LABA-2
  - make -j
  - cd ./bin/
  - ./test/test_tmatrix
notifications:
  email: false
